spring.application.name=tennis-club

spring.datasource.url=jdbc:h2:mem:tennisdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=demo
spring.datasource.password=demo

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

app.data-init-enabled=true
